#!/bin/bash
#SBATCH --job-name=vnn_train
#SBATCH --time=8:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --partition=volta-gpu
#SBATCH --gres=gpu:1
#SBATCH --qos=gpu_access
#SBATCH --mem=200G
#SBATCH --out=vnn_train_%j.out

module load python/3.12
source .venv/bin/activate

g2id="/proj/jchunglab/projects/genesight/bct_on_pgs/PGS001990/filtered/filtered_gene2id.txt"
train="/proj/jchunglab/projects/genesight/bct_on_pgs/PGS001990/filtered/train.pt"
test="/proj/jchunglab/projects/genesight/bct_on_pgs/PGS001990/filtered/test.pt"

python model/run_vnn.py -gene2id $g2id -train $train -test $test \
    -black_box True -hidden_layers 10 -lr 0.01 \
    -batchsize 32
